### ISSUE TITLE
Question: showNonNuclearChromosomes example, how does it work?

### ISSUE THREAD

**Issue by matthewchan15** [eweitz/ideogram#126] opened 2018-12-05 23:42 UTC
Hey @eweitz ,

I was trying to implement `showNonNuclearChromosomes` in my application, but it appears to not do much. I checked out the example you suggested to look at in the API [here](https://eweitz.github.io/ideogram/eukaryotes?org=sus-scrofa), but the example data set listed here does not load. I tried the source code for the example provided, and turning `showNonNuclearChromosomes` to off, but noticed no difference in all the working data sets in this application. Could you point me in the direction of a working data set for this feature? Thanks!

**Comment by eweitz** [comment] 2018-12-06 12:54
The failure of `showNonNuclearChromosomes` is caused by NCBI rate-limiting its E-Utils API.  The limits were enacted on 12/1, and [accommodated in Ideogram.js on 12/3](https://github.com/eweitz/ideogram/commits/master?after=b4455e4156a70608fcc6514f607bdb85d238f9be+0), unfortunately after the v1.4.0 release on 11/29.  

I'll likely release a patch, v1.4.1, in a few days so the fix for this bug in `master` is more widely available.

**Comment by eweitz** [comment] 2018-12-10 03:07
Version 1.4.1 is available, and this is fixed: https://eweitz.github.io/ideogram/eukaryotes?org=sus-scrofa.

**Closed by eweitz** 2018-12-10 03:07 UTC
