### ISSUE TITLE
annotations scale with brush

### ISSUE THREAD

**Issue by algarsi3** [eweitz/ideogram#131] opened 2019-01-02 11:53 UTC
When working with json annotation data I switch between two visualizations. The first one displays annotations on histogram:
![imagen](https://user-images.githubusercontent.com/14314257/50590751-7bfe8980-0e8c-11e9-8366-40e4ddd7c92c.png)
But when I switch the view to be able to use the brush, annotations scaling is not properly rendered:
![imagen](https://user-images.githubusercontent.com/14314257/50590790-a2bcc000-0e8c-11e9-8c0d-9ddefeb1c824.png)
The configuration I use is the following:

- Histogram view:
```typescript
{
      container: '#ideo-container',
      organism: 'organism',
      dataDir: '/assets/data/',
      annotationsColor: '#77F',
      annotationsLayout: 'histogram',
      rotatable: false,
      showBandLabels: false,
      annotationsPath: '/assets/data/' + code + '.json',
      chrMargin: 80,
      barWidth: 1,
      chrHeight: 600,
      histogramScaling: 'absolute'
};
```
- Brush view:
```typescript
{
      container: '#ideo-container',
      organism: 'organism',
      dataDir: '/assets/data/',
      annotationsColor: '#77F',
      annotationsLayout: 'histogram',
      rotatable: false,
      showBandLabels: false,
      annotationsPath: '/assets/data/' + code + '.json',
      chrMargin: 80,
      barWidth: 1,
      chrHeight: 1600,
      chromosome: '1',
      orientation: 'horizontal',
      brush: '1:1000000-2000000',
      onBrushMove: this.writeSelectedRange,
      onLoad: this.writeSelectedRange,
      histogramScaling: 'relative'
};
```

I tried changing scaling to absolute but the result is the same.

**Comment by eweitz** [comment] 2019-01-02 13:46
Can you link me to a reproducible example of this issue in a forked repo?

I cannot reproduce the problem locally.  When applying the annotations path in https://eweitz.github.io/ideogram/annotations-histogram to the example in https://eweitz.github.io/ideogram/brush, I see histograms with the expected scaling.

**Comment by eweitz** [comment] 2019-01-04 03:50
Closing for now.  Per above, I can't reproduce this.

If this is still a problem, please include a link to demonstrate the issue in a fork of this repo, isolating the issue and reducing your code as much as possible.

**Closed by eweitz** 2019-01-04 03:50 UTC

**Comment by algarsi3** [comment] 2019-01-04 08:34
Hello @eweitz, sorry for the delay, just solved it. The attribute causing problems was `chrMargin`. When removing from configuration object the annotations scale as expected.
